---
detectors:
  Attribute:
    enabled: false
    exclude: []
  BooleanParameter:
    enabled: false
    exclude: []
  ClassVariable:
    enabled: false # Rubocop already handles this
    exclude: []
  ControlParameter:
    enabled: false
    exclude: []
  DataClump:
    enabled: true
    exclude: []
    max_copies: 3
    min_clump_size: 3
  DuplicateMethodCall:
    enabled: true
    max_calls: 3
    allow_calls: []
    exclude:
    - spec # Specs contain a lot of duplication (better way?)
    - expect # Specs contain a lot of duplication (better way?)
    - logger # Calling logger often is a good thing
  FeatureEnvy:
    enabled: false
  IrresponsibleModule:
    enabled: false # We don't need Ruby comments for all modules
    exclude: []
  LongParameterList:
    enabled: true
    exclude: []
    max_params: 4 # 4 is used across our codebase
    overrides:
      initialize:
        max_params: 5
  LongYieldList:
    enabled: true
    exclude: []
    max_params: 3
  MissingSafeMethod:
    enabled: true
    exclude: []
  ModuleInitialize:
    enabled: true
    exclude: []
  NestedIterators:
    enabled: true
    exclude: []
    max_allowed_nesting: 2
    ignore_iterators:
    - tap
  NilCheck:
    enabled: false # Didn't appear helpful
    exclude: []
  RepeatedConditional:
    enabled: true
    exclude: []
    max_ifs: 2
  TooManyInstanceVariables:
    enabled: true
    exclude: []
    max_instance_variables: 6
  TooManyMethods:
    enabled: true
    exclude: []
    max_methods: 15
  TooManyStatements:
    enabled: true
    exclude:
    - initialize
    max_statements: 15
  TooManyConstants:
    enabled: false
  UncommunicativeMethodName:
    enabled: true
    exclude: []
    reject:
    - /^[a-z]$/
    - /[A-Z]/
    accept: []
  UncommunicativeModuleName:
    enabled: true
    exclude: []
    reject:
    - /^.$/
    - /[0-9]$/
  UncommunicativeParameterName:
    enabled: true
    exclude: []
    reject:
    - /^.$/
    - /[0-9]$/
    - /[A-Z]/
    - /^_/
    accept: []
  UncommunicativeVariableName:
    enabled: true
    exclude: []
    reject:
    - /[0-9]$/
    - /[A-Z]/
    accept:
    - _
  UnusedParameters:
    enabled: false # This is covered by Rubocop's Lint/UnusedMethodArgument
    exclude: []
  UtilityFunction:
    enabled: true
    public_methods_only: true
    exclude:
    - Concern # Concerns will frequently appear to have utility functions
    - Helper # Lots of helper methods do things like hash manipulation
    - "#change"
    - "#up"
    - "#down"
    - "#run"
    - "#work_message"

directories:
  "**/spec/**":
    UtilityFunction:
      enabled: false
    DuplicateMethodCall:
      enabled: false
  "**/jobs/**":
    UtilityFunction:
      enabled: false
  "**/workers/**":
    UtilityFunction:
      enabled: false
  "**/app/controllers/**":
    InstanceVariableAssumption:
      enabled: false
  "**/app/listeners/**":
    UtilityFunction:
      enabled: false
    DataClump:
      enabled: false
  "**/db/migrate/**":
    # Migrations contain generated class names so this reek makes no sense there
    UncommunicativeModuleName:
      enabled: false
