name: Reviewdog
on: [ pull_request ]
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 # v1.229.0
      with:
        ruby-version: 3.4.0
    - run: bundle check || bundle install
  # Temporarily disable
  #      - run: ./quality.sh

  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: shellcheck
      uses: reviewdog/action-shellcheck@f7921e489694b9d1fc5c3a843b414a95141fc380 # v1.19.0
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review # Change reporter.
        path: "." # Optional.
        pattern: "*.sh" # Optional.
        exclude: "./.git/*" # Optional.
